FROM node:20

WORKDIR /app

RUN npm install -g pnpm ts-node-dev

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5000

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/server.ts"]
