FROM node:20

WORKDIR /app

# نصب pnpm
RUN npm install -g pnpm

# کپی و نصب dependencies
COPY package*.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# کپی کل پروژه
COPY . .

EXPOSE 5000

# اجرای ts-node-dev با مسیر فایل اصلی
CMD ["pnpm", "exec", "ts-node-dev", "--respawn", "--transpile-only", "src/server.ts"]
